# -*- coding: utf-8 -*-
"""Task_Python_ Logic_ Building_ Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pl_PTNw5_tmTOfEPkE1CTRFqcmfkcS1_

#**Arjumand Afreen Tabinda**
# **Roll number:-** **411210**

##**Python Logic Building Problems with Physics Context**

###**Problem 1: Calculate Distance Using Speed and Time**
Problem Statement: Write a program to calculate the distance traveled by an object, given
its speed and the time it travels.
Formula:
Distance = Speed × Time
Input: Speed (in meters per second) and time (in seconds).
Output: Distance traveled (in meters).
Example:
Input: Speed = 10, Time = 5
Output: Distance = 50 meters
"""

# Formula  is : Distance = Speed × Time


speed =float(input("Enter speed in meters per second (m/s): "))


time=float(input("Enter time in seconds (s): "))


distance=speed*time


print(f"Distance traveled={distance} meters")

"""#**Problem 2: Calculate Force Using Newton’s Second Law**
Problem Statement: Write a program to calculate the force applied on an object using
Newton’s second law of motion.
Formula:
Force = Mass × Acceleration
Input: Mass (in kilograms) and acceleration (in meters per second squared).
Output: Force (in Newtons).
Example:
Input: Mass = 5, Acceleration = 3
Output: Force = 15 N

"""

#
#Formula is : Force=Mass  ×  Acceleration

mass =float(input("Enter mass in kilograms (kg): "))

acceleration =float(input("Enter acceleration in meters per second squared (m/s²): "))

force=mass*acceleration

print(f"Force applied ={force} Newtons (N)")

"""#**Problem 3: Gravitational Potential Energy**
Problem Statement: Write a program to calculate the gravitational potential energy of an
object.
Formula:
Potential Energy = m × g × h
where g = 9.8 m/s2 (acceleration due to gravity), m is the mass, and h is the height.
Input: Mass (in kilograms) and height (in meters).

Output: Gravitational potential energy (in joules).
Example:
Input: Mass = 2, Height = 10
Output: Potential Energy = 196 J
"""

# Formula is : Potential Energy =m × g × h


mass =float(input("Enter mass in kilograms (kg): "))


height =float(input("Enter height in meters (m): "))


g =9.8


potential_energy=mass*g*height


print(f"Gravitational Potential Energy ={potential_energy} Joules (J)")

"""#**Problem 4: Kinetic Energy of an Object**
Problem Statement: Write a program to calculate the kinetic energy of an object in motion.
Formula:
Kinetic Energy = 1/2 m v2
where m is the mass and v is the velocity.
Input: Mass (in kilograms) and velocity (in meters per second).
Output: Kinetic energy (in joules).
Example:
Input: Mass = 10, Velocity = 3
Output: Kinetic Energy = 45 J
"""

#Formula is : Kinetic Energy =(1/2)× mass × velocity²


mass =float(input("Enter mass in kilograms (kg): "))


velocity =float(input("Enter velocity in meters per second (m/s): "))


kinetic_energy =0.5 * mass * velocity ** 2


print(f"Kinetic Energy ={kinetic_energy} Joules (J)")

"""#**Problem 5: Ohm’s Law – Voltage Calculation**
Problem Statement: Write a program that calculates the voltage across a resistor given
current and resistance using Ohm’s Law.
Formula:
V = I × R
where V is voltage, I is current, and R is resistance.
Input: Current (in amperes) and resistance (in ohms).
Output: Voltage (in volts).
Example:
Input: Current = 2, Resistance = 5
Output: Voltage = 10 V
"""

#Formula is :V =I × R

current =float(input("Enter current in amperes (A): "))

resistance =float(input("Enter resistance in ohms (Ω): "))

voltage =current *resistance

print(f"Voltage across the resistor ={voltage} Volts (V)")

"""#**Problem 6: Projectile Motion – Maximum Height**
Problem Statement: Write a program to calculate the maximum height reached by a
projectile, given its initial velocity and launch angle (ignoring air resistance).
Formula:
h_max = (v2 × sin2(θ)) / (2g)
where v is the initial velocity, θ is the launch angle in degrees, and g = 9.8 m/s2.

Input: Initial velocity (in meters per second) and angle (in degrees).
Output: Maximum height (in meters).
Example:
Input: Velocity = 20, Angle = 45
Output: Height = 20.4 meters
"""

#Formula is : h_max =(v² × sin²(θ)) / (2 × g)

import  math

velocity =float(input("Please enter the initial velocity (in m/s): "))
angle_degrees =float(input("Please enter the launch angle (in degrees): "))
angle_radians =math.radians(angle_degrees)

g=9.8
height=(velocity ** 2)*(math.sin(angle_radians) ** 2)/(2 * g)

print(f"The maximum height reached by the projectile is:{height:.2f}meters")

"""# **Problem 7: Harmonic Oscillator – Period of a Spring**
Problem Statement: Write a program to calculate the period of a spring-mass system
(simple harmonic oscillator).
Formula:
T = 2π √(m/k)
where T is the period, m is the mass, and k is the spring constant.
Input: Mass (in kilograms) and spring constant k (in N/m).
Output: Period T (in seconds).
Example:
Input: Mass = 1, Spring constant = 50
Output: Period = 0.89 s
"""

#Formula: T = 2π × √(m / k)
import  math

mass =float(input("Please enter the mass of the object (in kg): "))
spring_constant = float(input("Please enter the spring constant (in N/m): "))
period=2 *math.pi *math.sqrt(mass / spring_constant)

print(f"The period of oscillation is: {period:.2f}seconds")

"""#**Problem 8: Free Fall – Time to Hit the Ground**
Problem Statement: Write a program to calculate the time it takes for an object to hit the
ground when dropped from a certain height (ignoring air resistance).
Formula:
t = √(2h/g)
where h is the height and g = 9.8 m/s2.
Input: Height (in meters).
Output: Time to hit the ground (in seconds).
Example:
Input: Height = 20
Output: Time = 2.02 seconds
"""

#Formula: t=√(2h / g)

import math

height=float(input("Please enter the height from which the object is dropped (in meters): "))

g=9.8

time=math.sqrt((2 * height) / g)


print(f"The time to hit the ground is:{time:.2f}seconds")

"""#**Problem 9: Work Done by a Force**
Problem Statement: Write a program to calculate the work done by a constant force acting
on an object.
Formula:
Work = F × d × cos(θ)

where F is the force, d is the displacement, and θ is the angle between the force and
displacement vectors.
Input: Force (in newtons), displacement (in meters), and angle (in degrees).
Output: Work done (in joules).
Example:
Input: Force = 100, Displacement = 10, Angle = 30
Output: Work = 866 J
"""

# Formula: Work = F × d × cos(θ)

import   math

force=float(input("Please enter the force applied (in newtons): "))

displacement=float(input("Please enter the displacement (in meters): "))

angle_degrees=float(input("Please enter the angle between force and displacement (in degrees): "))



angle_radians=math.radians(angle_degrees)

work_done=force *displacement * math.cos(angle_radians)

print(f"The work done by the force is:{round(work_done)} Joules (J)")

"""#**Problem 10: Power Consumption of a Device**
Problem Statement: Write a program to calculate the power consumed by an electrical
device.
Formula:
P = W / t
where P is power, W is work (energy), and t is time.
Input: Work (in joules) and time (in seconds).
Output: Power (in watts).
Example:
Input: Work = 500, Time = 50
Output: Power = 10 W
"""

#Formula will be used here:P=W/t

work=float(input("Please enter the amount of work done or energy used (in joules): "))

time=float(input("Please enter the time duration (in seconds): "))

power=work/time

print(f"The power consumed by the device is: {power:.2f}  watts (W)")